remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Artisan Choice project demo. Teddy ASSIH
description: This page is a for showing a demo of the Artisan Choice app.
